/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  webdomainsidebar: [{type: 'autogenerated', dirName: 'webhostingdomains'}],
  vserverrootserversidebar: [{type: 'autogenerated', dirName: 'vserverrootserver'}],
  dedicatedsidebar: [{type: 'autogenerated', dirName: 'dedicated'}],
  gameserversidebar: [{type: 'autogenerated', dirName: 'gameserver'}],
  dienstleistungensidebar: [{type: 'autogenerated', dirName: 'dienstleistungen'}],
  allgemeinsidebar: [{type: 'autogenerated', dirName: 'allgemein'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
